#!/usr/bin/env node

var index = require('./lib/index.js')


function escapeRegExp(str) {
  return str.replace(/[\/]/g, "\\$&");
}


var excludes = [], args = [], remap = {};
process.argv.each(function(arg, k){
  if(arg.startsWith('--exclude='))
    excludes.push(new RegExp(escapeRegExp(arg.stripStart('--exclude='))));

  if(arg.startsWith('--remap://')) {
    var map = arg.stripStart('--remap://').split('=');
    remap[map[0]] = map[1];
  }

  if(arg.startsWith('--')) ;
  else args.push(arg);
});

var cwd       = args[2] || process.cwd();
var start_dir = args[3] || "/" ;


var files = index.fetchSync(cwd, start_dir, excludes, remap);

process.stdout.write(JSON.stringify(files ));
