#!/usr/bin/env node

require('nyks');
var fs       = require('fs');
var glob      = require("glob");

var cwd       = process.argv[2] || process.cwd();
var start_dir =  process.argv[3] || "/" ;




// options is optional
var files_path = glob.sync("**", {cwd : cwd});
files_path = Object.combine(files_path, files_path);

var files = {};

Object.each(files_path, function(file_path, file_rel){
  var stats = fs.statSync(cwd + "/" + file_path)
  if(!stats.isFile())
    return;

  files[start_dir + file_path] = {
      'file_md5'   : fs.md5FileSync(cwd + "/" + file_path),
      'file_url'   : start_dir + file_path,
      'file_size'  : stats.size,
      'file_path'  : start_dir + file_path,
  };
});

process.stdout.write(JSON.stringify(files));
